#!/bin/sh

### This script will be executed when package installed and upgraded.
### Actions after package installed.
### ex. create database, create symbolic link...

curl -k https://bootstrap.pypa.io/get-pip.py | python3
pip install ffmpeg-python mutagen numpy

mkdir /flaccue
chown flaccue:flaccue /flaccue
chmod a+rwX /flaccue

exit 0
