#!/bin/sh

### This script will be executed when package installed and upgraded.
### Actions after package installed.
### ex. create database, create symbolic link...

mkdir /flaccue
chown flaccue:flaccue /flaccue
chmod a+rwX /flaccue

exit 0
